# Generated by Django 2.0.8 on 2019-06-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YoudaoResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50, verbose_name='单词')),
                ('text', models.CharField(max_length=200, verbose_name='文本')),
            ],
            options={
                'verbose_name': '有道',
                'verbose_name_plural': '有道',
            },
        ),
    ]
