# Generated by Django 2.0.8 on 2019-06-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_cj', models.CharField(max_length=255, verbose_name='中日')),
            ],
        ),
        migrations.CreateModel(
            name='YoudaoResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50, verbose_name='单词')),
                ('text_ec', models.CharField(max_length=255, verbose_name='英中')),
                ('text_ce', models.CharField(max_length=255, verbose_name='中英')),
                ('text_jc', models.CharField(max_length=255, verbose_name='日中')),
                ('text_cj', models.CharField(max_length=255, verbose_name='中日')),
                ('text_cj_list', models.ManyToManyField(to='dict_word.ContList', verbose_name='中日list')),
            ],
            options={
                'verbose_name': '有道',
                'verbose_name_plural': '有道',
            },
        ),
    ]
