# Generated by Django 2.0.8 on 2019-06-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict_word', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youdaoresult',
            name='text',
            field=models.CharField(max_length=255, verbose_name='文本'),
        ),
    ]
