# Generated by Django 2.0.8 on 2019-06-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict_word', '0002_auto_20190613_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youdaoresult',
            name='text',
        ),
        migrations.AddField(
            model_name='youdaoresult',
            name='text_ce',
            field=models.CharField(default='na', max_length=255, verbose_name='中英'),
        ),
        migrations.AddField(
            model_name='youdaoresult',
            name='text_cj',
            field=models.CharField(default='na', max_length=255, verbose_name='中日'),
        ),
        migrations.AddField(
            model_name='youdaoresult',
            name='text_ec',
            field=models.CharField(default='na', max_length=255, verbose_name='英中'),
        ),
        migrations.AddField(
            model_name='youdaoresult',
            name='text_jc',
            field=models.CharField(default='na', max_length=255, verbose_name='日中'),
        ),
    ]
